# Generated by Django 4.1.7 on 2023-09-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch5app', '0005_accounts_book_category_in_exp_items_daily_ledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='share_holders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_holders_name', models.CharField(max_length=200)),
                ('share_holders_percentage', models.CharField(max_length=200)),
            ],
        ),
    ]
