# Generated by Django 4.1.7 on 2023-04-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_pg1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roon_no', models.IntegerField()),
                ('room_name', models.CharField(max_length=100)),
                ('share_type', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
