# Generated by Django 4.1.7 on 2023-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch2app', '0004_pg1_new_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch_closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=200)),
                ('jan', models.CharField(max_length=200)),
                ('feb', models.CharField(max_length=200)),
                ('mar', models.CharField(max_length=200)),
                ('apr', models.CharField(max_length=200)),
                ('may', models.CharField(max_length=200)),
                ('jun', models.CharField(max_length=200)),
                ('jul', models.CharField(max_length=200)),
                ('aug', models.CharField(max_length=200)),
                ('sep', models.CharField(max_length=200)),
                ('oct', models.CharField(max_length=200)),
                ('nov', models.CharField(max_length=200)),
                ('dec', models.CharField(max_length=200)),
                ('flag', models.CharField(max_length=200)),
            ],
        ),
    ]
