# Generated by Django 4.1.7 on 2023-08-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_accounts_book_category_in_exp_items_daily_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_exp_items_daily',
            name='item_catergory',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
