# Generated by Django 4.1.7 on 2023-08-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_accounts_book_deleted_by_accounts_book_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='updated_by',
            new_name='updated_bys',
        ),
    ]
