# Generated by Django 4.1.7 on 2023-08-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_updated_by_table1_updated_bys'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='cb_date',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table1',
            name='db_date',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table1',
            name='ub_date',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
