# Generated by Django 4.1.7 on 2023-08-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_accounts_book_cb_date_accounts_book_db_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_book',
            name='ub_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='ub_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='in_exp_items_daily',
            name='ub_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger',
            name='ub_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opening_balance',
            name='ub_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table1',
            name='ub_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
