# Generated by Django 4.1.7 on 2024-01-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch10app', '0002_share_holders'),
    ]

    operations = [
        migrations.AddField(
            model_name='share_holders',
            name='share_holders_amt_total',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share_holders',
            name='share_holders_rent',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
