# Generated by Django 4.1.7 on 2023-06-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch4app', '0002_pg1_new_beds_april_dis_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg1_new_guest',
            name='april_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg1_new_guest',
            name='auguest_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg1_new_guest',
            name='dec_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg1_new_guest',
            name='feb_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg1_new_guest',
            name='jan_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg1_new_guest',
            name='july_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg1_new_guest',
            name='june_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg1_new_guest',
            name='march_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg1_new_guest',
            name='may_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg1_new_guest',
            name='nov_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg1_new_guest',
            name='october_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg1_new_guest',
            name='sept_dis_amt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
